### ISSUE TITLE
Issues running on Node greater than 20

### ISSUE THREAD

**Issue by mryechkin** [twofold-rsc/twofold#16]
This is cool! Excited to try it out.

One thing that I immediately ran into though is it seems to only want to run on Node 20, and not Node 20+ as it says.

I'm on a Mac using Node 22 (via `nvm`) and got these error messages - both when initially running `create twofold-app`:

<img width="961" alt="Screenshot 2024-08-21 at 8 46 16 PM" src="https://github.com/user-attachments/assets/2d3b4ae8-e9b8-4605-ae2f-3aab22e8f0af">

and then also when trying to run `dev`:

<img width="523" alt="Screenshot 2024-08-21 at 8 48 11 PM" src="https://github.com/user-attachments/assets/f2a95d68-f814-4c79-b24a-ab1f69d5cdeb">

I'm guessing this has something to do with how the `engines` field in `package.json` is being resolved? I usually have to list out specific major versions explicitly, never seemed to work with just `>20`:

```json
"engines": {
  "node": ">=20 || >= 22"
}
```

It worked after I switched to Node 20.

**Comment by WahyuIndG** [comment]
@ryanto  I encountered a problem like the following, I tried to downgrade nodejs to 20.9.0 but the problem was not resolved. Is there anything I need to do? Thank you 

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:249:11)
    at defaultLoad (node:internal/modules/esm/load:130:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:553:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:434:56)
    at new ModuleJob (node:internal/modules/esm/module_job:71:27)
    at #createModuleJob (node:internal/modules/esm/loader:447:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:259:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:17)
    at async ModuleLoader.import (node:internal/modules/esm/loader:472:23) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
🏗️  Built app in 602.56ms [version: 95ff0c595632]
🚀 Server listening on http://0.0.0.0:3000/

**Comment by WahyuIndG** [comment]
Windows 11 Version 23H2 (0S Build 22631.4169)

**Comment by ryanto** [comment]
Hi @WahyuIndG your issue should be all fixed now! In your `package.json` file change the `@twofold/framework` version to `0.0.27` and run `pnpm install`.

Thanks for reporting the issue, really appreciate it. Let me know if you continue to run into any more issues.

**Comment by ryanto** [comment]
Finally figured this one out! Should be fixed w/ `pnpm create twofold-app@latest` now.
